### ISSUE TITLE
tightfigadv raises error

### ISSUE THREAD

**Issue by lpk-py** [JacobD10/tightfigadv#2]
```
Error using cellfun
Input #2 expected to be a cell array, was double
instead.

Error in tightfigadv (line 64)
origtxparunits = cellfun(@(x) x.Units, htxPar,
'un', 0);

Error in tightfig (line 2)
function hfig=tightfig(hfig),if
nargin==0,hfig=gcf;end;hfig=tightfigadv(hfig);end

```

`htxPar` is empty.

**Comment by jdonley** [comment]
Hi lileipku00, do you have a minimum working example that I can use to reproduce the error? Then I can see how the error occurs. Thanks.

**Comment by lpk-py** [comment]
Sorry I didn't save the figure and now I cannot reproduce the error.

I'll upload an example when I encounter it again.

**Comment by jdonley** [comment]
No problem. When you manage to reproduce the error just reopen this issue and I’ll look into it for you.
